[package]
name = "rust-minio"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dotenv = "0.15"
futures = "0.3.31"
reqwest = "0.12.24"
tokio = { version = "1", features = ["full"] }
minio = "0.3.0"
tokio-stream = "0.1.17"

